name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9.0
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - diffusers==0.11.1
    - pytorch_lightning==1.5.9
    - opencv-python
    - pudb
    - datasets==2.8.0
    - torchmetrics==0.6.0
    - seaborn
    - invisible-watermark==0.1.5
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.5.9
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.3.0
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.6.0
    - gradio==3.20.0
    - torch-fidelity==0.3.0
    - transformers==4.27.4
    - torchmetrics==0.6.0
    - kornia==0.6.8
    - k-diffusion==0.0.14
    - gradio
    - open-clip-torch
    - jieba
    - ninja
    - pycocotools
    - IPython
    - matplotlib
    - onnxruntime
    - onnx
    - openai
    - webdataset==0.2.35
    - safetensors==0.3.0
    - timm
    - basicsr==1.4.2
    - revChatGPT
    - streamlit
    - -e git+https://github.com/facebookresearch/segment-anything@main#egg=segment-anything
