name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9.0
  - pip=20.3
  - cudatoolkit=11.8
  - pytorch=2.1.0
  - torchvision==0.16.0
  - torchaudio==2.1.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - diffusers==0.11.1
    - pytorch_lightning==1.5.9
    - opencv-python==4.8.1.78
    - pillow==9.4.0
    - pyyaml==6.0.1
    - json_tricks==3.17.3
    - pudb
    - datasets==2.8.0
    - torchmetrics==0.6.0
    - seaborn
    - invisible-watermark==0.1.5
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.5.9
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.3.0
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - gradio==3.20.0
    - torch-fidelity==0.3.0
    - transformers==4.34.0
    - torchmetrics==0.6.0
    - ftfy==6.1.1
    - regex==2023.10.3
    - nltk==3.8.1
    - vision-datasets==0.2.2
    - cython==3.0.2
    - pycocotools==2.0.7
    - diffdist==0.1
    - pyarrow==13.0.0
    - cityscapesscripts==2.2.2
    - shapely==1.8.0
    - scikit-image==0.21.0
    - mup==1.0.0
    - sentencepiece==0.1.99
    - kornia==0.6.8
    - k-diffusion==0.0.14
    - gradio
    - open-clip-torch
    - jieba
    - ninja
    - pycocotools
    - IPython
    - matplotlib
    - onnxruntime
    - onnx
    - openai
    - webdataset==0.2.35
    - safetensors==0.3.0
    - timm
    - basicsr==1.4.2
    - revChatGPT
    - streamlit
    - scikit-learn==1.3.1
    - timm==0.4.12
    - fvcore==0.1.5.post20221221
    - -e git+https://github.com/facebookresearch/segment-anything@main#egg=segment-anything
    - -e git+https://github.com/arogozhnikov/einops.git@master#egg=einops
    - -e git+https://github.com/openai/whisper.git@main#egg=whisper
# https://github.com/MaureenZOU/detectron2-xyz